// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_sf73u8jTfST9-iBNtd_ZSO0qeV3kZLA',
    appId: '1:1076555351434:web:fe70e58dc0d629f539f473',
    messagingSenderId: '1076555351434',
    projectId: 'flutter---notifications',
    authDomain: 'flutter---notifications.firebaseapp.com',
    storageBucket: 'flutter---notifications.firebasestorage.app',
    measurementId: 'G-HTXHGDD4TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWrA1hbfvjO4fS3cEqDO0m3VjbWLG0UtE',
    appId: '1:1076555351434:android:797625914ab144c739f473',
    messagingSenderId: '1076555351434',
    projectId: 'flutter---notifications',
    storageBucket: 'flutter---notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbFApkJDD-XZ5foXYhsthKvUG522x-Pxo',
    appId: '1:1076555351434:ios:0641e395a1dafcec39f473',
    messagingSenderId: '1076555351434',
    projectId: 'flutter---notifications',
    storageBucket: 'flutter---notifications.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbFApkJDD-XZ5foXYhsthKvUG522x-Pxo',
    appId: '1:1076555351434:ios:0641e395a1dafcec39f473',
    messagingSenderId: '1076555351434',
    projectId: 'flutter---notifications',
    storageBucket: 'flutter---notifications.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_sf73u8jTfST9-iBNtd_ZSO0qeV3kZLA',
    appId: '1:1076555351434:web:293a941bb158a38739f473',
    messagingSenderId: '1076555351434',
    projectId: 'flutter---notifications',
    authDomain: 'flutter---notifications.firebaseapp.com',
    storageBucket: 'flutter---notifications.firebasestorage.app',
    measurementId: 'G-XBL5X9KMS8',
  );
}
